"""empty message

Revision ID: 66cb93a66d6b
Revises: 
Create Date: 2020-08-28 00:55:33.454331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66cb93a66d6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('neibour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dx', sa.Integer(), nullable=True),
    sa.Column('dy', sa.Integer(), nullable=True),
    sa.Column('echo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dx'),
    sa.UniqueConstraint('dy'),
    sa.UniqueConstraint('echo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('neibour')
    # ### end Alembic commands ###
